import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import _navbar from '../components/_navbar';
import _form from '../components/_form';
// import _designcard from '../components/_designcard';
// import _vistacard from '../components/_vistacard';
// import _saleablecard from '../components/_saleablecard';
// import _expocard from '../components/_expocard';
// import _productathoncard from '../components/_productathoncard';
// import _ideastormcard from '../components/_ideastormcard';
// import _useEffect from './api/_fetchdata';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E-Summit 22 ||  Events</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


<div className="parent">
  <div className="header">
    <div className="headericon_a"><img className="Esummitlogo" src="Esummitlogofinal.webp" /></div>

    <_navbar/>
    
    <div className="headericon_b">LOG IN or REGISTER</div>
  </div>
  <div className="events">
    <div className="events_content">Events</div>
    </div>
  <div className="body">
    <div className="cardrowfirst">
      <div className="card1"><img className="cardimg" src="design.png"/></div>
     

      <div className="card1"><img className="cardimg" src="ideastorm.png"/></div>
      <div className="cardimg" id="cardgo1"><img className="card1" src="Productathon.png"/></div>
    </div>
    <div className="cardrowsecond">
      <div className="cardimg"><img className="card1" src="saleable.png"/></div>
      <div className="cardimg"><img className="card1" src="expo.png"/></div>
      <div className="cardimg" id="cardgo2"><img className="card1" src="vista.png"/></div>
    </div>

  </div>
  <div className="footer">
    <div className="contact_a">
      <div className="footerlogoemail_a"><img src="Esummitlogofinal.webp" className="Esummitlogo2"/></div>
      <div className="footerlogoemail_b">EMAIL<br/>esummit@iitr.ac.in</div>
      <div className="footerfollowus">
        <div className="footerfollowus_first">Follow us at</div>
        <div className="footerfollowus_second">
          <div className="footerfollowusicon"><img src="facebook.webp"/></div>
          <div className="footerfollowusicon"><img src="Instagram.webp"/></div>
          <div className="footerfollowusicon"><img src="Twitter.PNG"/></div>
          <div className="footerfollowusicon"><img src="linkedIN.webp"/></div>
        </div>
        <div className="footerfollowus_second">
          <div className="footerfollowusiconsecond"><img src="youtube.webp"/></div>
          <div className="footerfollowusiconthird"></div>
        </div>
        <div className="footerfollowus_second"></div>

      </div>
    </div>
    <div className="contact_b">
      <div className="footerecelllogo"><img src="Ecelllogo.webp" className="Ecelllogo"/></div>
      <div className="footercontacts">PHONE<br/>Daksh:<br/>+919646583392<br/>Abinandan:<br/>+918054689033</div>
      <div className="footeraddress">OUR ADDRESS<br/>E-Cell Office SAC<br/>Building<br/>IIT Roorkee<br/>Uttrakhand-<br/>247667,INDIA</div>
    </div>
    <div className="form"><_form/></div>
  </div>
</div>

    </div>
  )
}
